.TH popt l
.ER
.SH NAME
popt \- identify p-optimal structures in RNAsubopt output
.SH SYNOPSIS
\fBpopt

.SH DESCRIPTION
.I popt
reads suboptimal structures as produced by RNAsubopt from stdin and prints
to stdout all structures that are p-optimal, i.e. structures that contain
at least one base pair that is not contained in any structure of better energy.
The list of structures has to be sorted by energy and the first structure
should be preceded by a line containing the sequence.

On output a structure is followed by its energy and a list of all base
pairs occuring for the first time in that structure.
If a base pair occurs for the first time in several structures of equal
energy, only the first of those structures is returned.

.SH EXAMPLE
   RNAsubopt -s -e 5 < seq_file | popt
